// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/v1/users/login-post': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/login-post').default>>>>
    }
    '/api/v1/users/send-auth': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/send-auth').default>>>>
    }
    '/api/v1/users/sign-up': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/v1/users/sign-up.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.7.4/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}