version: "3.8"

services:
  nuxt:
    build: ./
    restart: always
    ports:
      - "3000:3000"
      # - "9200:9200"
      # - "9300:9300"
      # - "9222:9222"
      # - "9333:9333"

    command:
      "npm run start"
    container_name: nuxt
    networks:
      - esnet

networks:
  esnet:
